image: mtiller/book-builder

variables:
    GIT_SUBMODULE_STRATEGY: normal

cache:
    paths:
        - text/results
        - text/plots

stages:
    - specs
    - results
    - docs_json
    - docs_ebooks
    - docs_pdf
    - docs_site
    - docs_html

generate_specs:
    stage: specs
    script:
        - (cd text; make specs)

generate_results:
    stage: results
    script:
        - (cd text; make results)
    artifacts:
        paths:
            - text/results/exes.tar.gz
            - text/plots

generate_json:
    stage: docs_json
    script:
        - (cd text; make json)
    artifacts:
        paths:
            - text/build/

generate_ebooks:
    stage: docs_ebooks
    script:
        - (cd text; make ebooks)
    artifacts:
        paths:
            - text/build/

generate_pdfs:
    stage: docs_pdf
    script:
        - (cd text; make pdf pdf-a4)
    artifacts:
        paths:
            - text/build/

generate_site:
    image: node:10-jessie
    stage: docs_site
    script:
        - make ng_site
    artifacts:
        paths:
            - nextgen/out

generate_html:
    stage: docs_html
    script:
        - (cd text; make dirhtml)
    artifacts:
        paths:
            - text/build/
