image: mtiller/book-builder

cache:
    paths:
        - text/results
        - text/plots

stages:
    - specs
    - results
    - docs_html
    - docs_json
    - docs_ebooks
    - docs_pdf

generate_specs:
    stage: specs
    script:
        - (cd text; make specs)

generate_results:
    stage: results
    script:
        - (cd text; make results)

generate_html:
    stage: docs_html
    script:
        - (cd text; make dirhtml)
    artifacts:
        paths:
            - text/build/

generate_json:
    stage: docs_json
    script:
        - (cd text; make json)
    artifacts:
        paths:
            - text/build/

generate_ebooks:
    stage: docs_ebooks
    script:
        - (cd text; make ebooks)
    artifacts:
        paths:
            - text/build/

generate_pdfs:
    stage: docs_pdf
    script:
        - (cd text; make pdf pdf-a4)
    artifacts:
        paths:
            - text/build/
